### ISSUE TITLE
Not working with android USB tethering or hotspot

### ISSUE THREAD

**Issue by skymaze** [esteve/ros2_android_examples#21]
When PC and android phone are connected to a router, works fine. But when PC is connected to the android phone with android hotspot or USB tethering, PC and android can not discover each other's topics. Any ideas？Thanks.

**Comment by meverg** [comment]
Hey @skymaze could you find a solution to this issue

**Comment by skymaze** [comment]
> Hey @skymaze could you find a solution to this issue

No, considering that ros_java is too complicated for my needs and lacks support, I finally chose to write a simple grpc server/client to pass messages.

This project is a good example [cyberdog_grpc](https://github.com/MiRoboticsLab/cyberdog_ros2/tree/main/cyberdog_common/cyberdog_grpc)

**Comment by meverg** [comment]
Thanks for the suggestion @skymaze 
After trying a few things I remembered [this warning](https://github.com/ros2-java/ros2_java#including-android) and it worked for me 🎉  
Maybe it can for you too:

> Add the snippet below in your ~/.bashrc file
> 
> ```
> # This ros2 middleware implementation is a must-have for compliance with the ros2-java client
> export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
> ```
