### ISSUE TITLE
ROS2 communication fails on android via ethernet cable

### ISSUE THREAD

**Issue by onleejk** [esteve/ros2_android_examples#6]
Hi, I'm Junkyu. I'm testing ROS2 communication between android and PC.
device environment: 
1. Samsung Galaxy S8 with ethernet port using OTG and USB2ETH adapter.
2. Ubuntu Desktop with ros2
3. AP

mobile and PC can communicate ROS2 msgs when mobile connected via wi-fi.
but via ethernet cable, mobile can't publish and subscribe any msg.
I checked ethernet is working, mobile got ip address and can load web sites.

If someone knows why it occurs or any solution. please help me.

**Comment by onleejk** [comment]
it works sorry. the reason was ap setting (multicast forwarding)

**Comment by esteve** [comment]
@onleejk sorry for the slow response. Thanks for the followup.
